### Simple Example

In [43]:
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.feature_extraction import text
import pandas as pd

In [44]:
print(sorted(text.ENGLISH_STOP_WORDS))

['a', 'about', 'above', 'across', 'after', 'afterwards', 'again', 'against', 'all', 'almost', 'alone', 'along', 'already', 'also', 'although', 'always', 'am', 'among', 'amongst', 'amoungst', 'amount', 'an', 'and', 'another', 'any', 'anyhow', 'anyone', 'anything', 'anyway', 'anywhere', 'are', 'around', 'as', 'at', 'back', 'be', 'became', 'because', 'become', 'becomes', 'becoming', 'been', 'before', 'beforehand', 'behind', 'being', 'below', 'beside', 'besides', 'between', 'beyond', 'bill', 'both', 'bottom', 'but', 'by', 'call', 'can', 'cannot', 'cant', 'co', 'con', 'could', 'couldnt', 'cry', 'de', 'describe', 'detail', 'do', 'done', 'down', 'due', 'during', 'each', 'eg', 'eight', 'either', 'eleven', 'else', 'elsewhere', 'empty', 'enough', 'etc', 'even', 'ever', 'every', 'everyone', 'everything', 'everywhere', 'except', 'few', 'fifteen', 'fifty', 'fill', 'find', 'fire', 'first', 'five', 'for', 'former', 'formerly', 'forty', 'found', 'four', 'from', 'front', 'full', 'further', 'get', 'give', 'go', 'had', 'has', 'hasnt', 'have', 'he', 'hence', 'her', 'here', 'hereafter', 'hereby', 'herein', 'hereupon', 'hers', 'herself', 'him', 'himself', 'his', 'how', 'however', 'hundred', 'i', 'ie', 'if', 'in', 'inc', 'indeed', 'interest', 'into', 'is', 'it', 'its', 'itself', 'keep', 'last', 'latter', 'latterly', 'least', 'less', 'ltd', 'made', 'many', 'may', 'me', 'meanwhile', 'might', 'mill', 'mine', 'more', 'moreover', 'most', 'mostly', 'move', 'much', 'must', 'my', 'myself', 'name', 'namely', 'neither', 'never', 'nevertheless', 'next', 'nine', 'no', 'nobody', 'none', 'noone', 'nor', 'not', 'nothing', 'now', 'nowhere', 'of', 'off', 'often', 'on', 'once', 'one', 'only', 'onto', 'or', 'other', 'others', 'otherwise', 'our', 'ours', 'ourselves', 'out', 'over', 'own', 'part', 'per', 'perhaps', 'please', 'put', 'rather', 're', 'same', 'see', 'seem', 'seemed', 'seeming', 'seems', 'serious', 'several', 'she', 'should', 'show', 'side', 'since', 'sincere', 'six', 'sixty', 'so', 'some', 'somehow', 'someone', 'something', 'sometime', 'sometimes', 'somewhere', 'still', 'such', 'system', 'take', 'ten', 'than', 'that', 'the', 'their', 'them', 'themselves', 'then', 'thence', 'there', 'thereafter', 'thereby', 'therefore', 'therein', 'thereupon', 'these', 'they', 'thick', 'thin', 'third', 'this', 'those', 'though', 'three', 'through', 'throughout', 'thru', 'thus', 'to', 'together', 'too', 'top', 'toward', 'towards', 'twelve', 'twenty', 'two', 'un', 'under', 'until', 'up', 'upon', 'us', 'very', 'via', 'was', 'we', 'well', 'were', 'what', 'whatever', 'when', 'whence', 'whenever', 'where', 'whereafter', 'whereas', 'whereby', 'wherein', 'whereupon', 'wherever', 'whether', 'which', 'while', 'whither', 'who', 'whoever', 'whole', 'whom', 'whose', 'why', 'will', 'with', 'within', 'without', 'would', 'yet', 'you', 'your', 'yours', 'yourself', 'yourselves']

In [45]:
sentences = [
    "The food is good",
    "The food is not good good",
]

sentences

['The food is good', 'The food is not good good']

In [46]:
vectorizer = CountVectorizer(
    stop_words="english"
)

X = vectorizer.fit_transform(
    sentences
)

X

<Compressed Sparse Row sparse matrix of dtype 'int64'
	with 4 stored elements and shape (2, 2)>

In [47]:
print(vectorizer.get_feature_names_out())
print(vectorizer.vocabulary_)
print(X.toarray())

['food' 'good']
{'food': 0, 'good': 1}
[[1 1]
 [1 2]]

In [48]:
X.toarray()

array([[1, 1],
       [1, 2]])

In [74]:
df = pd.DataFrame(
    X.toarray(),
    columns=vectorizer.get_feature_names_out(),
    index=sentences,
)

def clean_data(sentences):
    
    cleaned  = []

    lower_sentences = [ sent.lower() for sent in sentences ]

    for sent in lower_sentences:
        words = sent.split(" ")
        sent = [ word for word in words if word not in text.ENGLISH_STOP_WORDS ]  
        cleaned.append(" ".join(sent))
        
    return cleaned
        
df.insert(0, "cleaned", clean_data(sentences))
df

                                  cleaned  food  good
The food is good                food good     1     1
The food is not good good  food good good     1     2

### Example 2 with n_grams

In [102]:
sentences_2 = [
    "He is a good Boy",
    "She is a good girl",
    "Boy and girl are good",
    "I love boy and girl",
    "just extras to increase sentences to get to four n_grams"
]
sentences_2

['He is a good Boy',
 'She is a good girl',
 'Boy and girl are good',
 'I love boy and girl',
 'just extras to increase sentences to get to four n_grams']

In [103]:
vectorizer2 = CountVectorizer(
    stop_words="english",
)
vectors = vectorizer2.fit_transform(sentences_2)
vectors

<Compressed Sparse Row sparse matrix of dtype 'int64'
	with 15 stored elements and shape (5, 9)>

In [104]:
feature_names2 = vectorizer2.get_feature_names_out()
feature_names2

array(['boy', 'extras', 'girl', 'good', 'increase', 'just', 'love',
       'n_grams', 'sentences'], dtype=object)

In [105]:
vectors.toarray()

array([[1, 0, 0, 1, 0, 0, 0, 0, 0],
       [0, 0, 1, 1, 0, 0, 0, 0, 0],
       [1, 0, 1, 1, 0, 0, 0, 0, 0],
       [1, 0, 1, 0, 0, 0, 1, 0, 0],
       [0, 1, 0, 0, 1, 1, 0, 1, 1]])

In [106]:
df_2 = pd.DataFrame(
    data=vectors.toarray(),
    columns=feature_names2,
    index=sentences_2
)

df_2.insert(0, "cleaned data", clean_data(sentences_2))
df_2

,cleaned data,boy,extras,girl,good,increase,just,love,n_grams,sentences
He is a good Boy,good boy,1,0,0,1,0,0,0,0,0
She is a good girl,good girl,0,0,1,1,0,0,0,0,0
Boy and girl are good,boy girl good,1,0,1,1,0,0,0,0,0
I love boy and girl,love boy girl,1,0,1,0,0,0,1,0,0
just extras to increase sentences to get to four n_grams,just extras increase sentences n_grams,0,1,0,0,1,1,0,1,1

In [120]:
def with_n_grams(n_grams=(1,1)):
    vectorizer = CountVectorizer(
        stop_words="english",
        ngram_range=n_grams,
    )
    vectors = vectorizer.fit_transform(sentences_2)
    feature_names = vectorizer.get_feature_names_out()
    
    df_2 = pd.DataFrame(
        data=vectors.toarray(),
        columns=feature_names,
        index=clean_data(sentences_2)
    )

    return df_2

In [125]:
# (1,1) is the default: every feature is a single word — a unigram
with_n_grams()

,boy,extras,girl,good,increase,just,love,n_grams,sentences
good boy,1,0,0,1,0,0,0,0,0
good girl,0,0,1,1,0,0,0,0,0
boy girl good,1,0,1,1,0,0,0,0,0
love boy girl,1,0,1,0,0,0,1,0,0
just extras increase sentences n_grams,0,1,0,0,1,1,0,1,1

In [126]:
# (1,2): unigrams + bigrams — single words and adjacent word pairs
with_n_grams(n_grams=(1,2))

,boy,boy girl,extras,extras increase,girl,girl good,good,good boy,good girl,increase,increase sentences,just,just extras,love,love boy,n_grams,sentences,sentences n_grams
good boy,1,0,0,0,0,0,1,1,0,0,0,0,0,0,0,0,0,0
good girl,0,0,0,0,1,0,1,0,1,0,0,0,0,0,0,0,0,0
boy girl good,1,1,0,0,1,1,1,0,0,0,0,0,0,0,0,0,0,0
love boy girl,1,1,0,0,1,0,0,0,0,0,0,0,0,1,1,0,0,0
just extras increase sentences n_grams,0,0,1,1,0,0,0,0,0,1,1,1,1,0,0,1,1,1

In [132]:
# (1,3): unigrams + bigrams + trigrams — runs of 1, 2, and 3 adjacent words
with_n_grams(n_grams=(1,3))

,boy,boy girl,boy girl good,extras,extras increase,extras increase sentences,girl,girl good,good,good boy,...,increase sentences n_grams,just,just extras,just extras increase,love,love boy,love boy girl,n_grams,sentences,sentences n_grams
good boy,1,0,0,0,0,0,0,0,1,1,...,0,0,0,0,0,0,0,0,0,0
good girl,0,0,0,0,0,0,1,0,1,0,...,0,0,0,0,0,0,0,0,0,0
boy girl good,1,1,1,0,0,0,1,1,1,0,...,0,0,0,0,0,0,0,0,0,0
love boy girl,1,1,0,0,0,0,1,0,0,0,...,0,0,0,0,1,1,1,0,0,0
just extras increase sentences n_grams,0,0,0,1,1,1,0,0,0,0,...,1,1,1,1,0,0,0,1,1,1

In [ ]:
# (2,3): bigrams + trigrams only — single words are dropped
with_n_grams(n_grams=(2,3))

,boy girl,boy girl good,extras increase,extras increase sentences,girl good,good boy,good girl,increase sentences,increase sentences n_grams,just extras,just extras increase,love boy,love boy girl,sentences n_grams
good boy,0,0,0,0,0,1,0,0,0,0,0,0,0,0
good girl,0,0,0,0,0,0,1,0,0,0,0,0,0,0
boy girl good,1,1,0,0,1,0,0,0,0,0,0,0,0,0
love boy girl,1,0,0,0,0,0,0,0,0,0,0,1,1,0
just extras increase sentences n_grams,0,0,1,1,0,0,0,1,1,1,1,0,0,1

In [130]:
# (2,4): bigrams, trigrams, and 4-grams
with_n_grams(n_grams=(2,4))

,boy girl,boy girl good,extras increase,extras increase sentences,extras increase sentences n_grams,girl good,good boy,good girl,increase sentences,increase sentences n_grams,just extras,just extras increase,just extras increase sentences,love boy,love boy girl,sentences n_grams
good boy,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0
good girl,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0
boy girl good,1,1,0,0,0,1,0,0,0,0,0,0,0,0,0,0
love boy girl,1,0,0,0,0,0,0,0,0,0,0,0,0,1,1,0
just extras increase sentences n_grams,0,0,1,1,1,0,0,0,1,1,1,1,1,0,0,1