In [2]:
import pandas as pd

dic = {
    "Name": ["Abdulkareem", "Khem", "Adams"],
    "Age": [23, 18, 26],
    "Gender": ["Male", "Female", "Male"],
}

df = pd.DataFrame(dic)

df

          Name  Age  Gender
0  Abdulkareem   23    Male
1         Khem   18  Female
2        Adams   26    Male

In [3]:
print(df.iloc[0])
print("==================")
print(df.iloc[0]["Name"])

Name      Abdulkareem
Age                23
Gender           Male
Name: 0, dtype: object
==================
Abdulkareem

In [4]:
type(df.iloc[0])

pandas.core.series.Series

In [5]:
df["Age"]

0    23
1    18
2    26
Name: Age, dtype: int64

In [6]:
type(df["Age"])

pandas.core.series.Series

In [7]:

print(df)
print(df.describe())

          Name  Age  Gender
0  Abdulkareem   23    Male
1         Khem   18  Female
2        Adams   26    Male
             Age
count   3.000000
mean   22.333333
std     4.041452
min    18.000000
25%    20.500000
50%    23.000000
75%    24.500000
max    26.000000

In [8]:
dic = {
    "Name": ["Abdulkareem", "Khem", "Adams"],
    "Age": [23, 18, 26],
    "Gender": ["Male", "Female", "Male"],
    "Weight": [34,12.67,9.3]
}

df = pd.DataFrame(dic)

print(df)
df.describe()

          Name  Age  Gender  Weight
0  Abdulkareem   23    Male   34.00
1         Khem   18  Female   12.67
2        Adams   26    Male    9.30

             Age     Weight
count   3.000000   3.000000
mean   22.333333  18.656667
std     4.041452  13.394127
min    18.000000   9.300000
25%    20.500000  10.985000
50%    23.000000  12.670000
75%    24.500000  23.335000
max    26.000000  34.000000

In [9]:
df

          Name  Age  Gender  Weight
0  Abdulkareem   23    Male   34.00
1         Khem   18  Female   12.67
2        Adams   26    Male    9.30

In [10]:
#  df["Age"] == 23
df[ [ True, False, True ] ]

          Name  Age Gender  Weight
0  Abdulkareem   23   Male    34.0
2        Adams   26   Male     9.3

In [11]:
df[ df["Age"] >= 23 ]

          Name  Age Gender  Weight
0  Abdulkareem   23   Male    34.0
2        Adams   26   Male     9.3

In [12]:
print(df.head(1)) # By default gives the first five (5) rows
print("===========")
print(df.tail(1)) # By default gives the last five (5) rows
print("===========")
print(df.info(1))
print("===========")
print(df.index)
print("===========")
print(df.columns)

          Name  Age Gender  Weight
0  Abdulkareem   23   Male    34.0
===========
    Name  Age Gender  Weight
2  Adams   26   Male     9.3
===========
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    3 non-null      object
 1   Age     3 non-null      int64
 2   Gender  3 non-null      object
 3   Weight  3 non-null      float64
dtypes: float64(1), int64(1), object(2)
memory usage: 228.0+ bytes
None
===========
RangeIndex(start=0, stop=3, step=1)
===========
Index(['Name', 'Age', 'Gender', 'Weight'], dtype='object')

In [13]:
df

          Name  Age  Gender  Weight
0  Abdulkareem   23    Male   34.00
1         Khem   18  Female   12.67
2        Adams   26    Male    9.30

In [44]:
df.loc[ (df["Age"] == 18) | (df["Name"].str.endswith("m")) ]

          Name  Age Gender  Weight
0  Abdulkareem   23   Male   34.00
1         Khem   18   Male   12.67

In [55]:
df.loc[ (df["Age"] == 18) | (df["Name"].str.endswith("m")), "Gender" ] = "M"

In [56]:
df

          Name  Age Gender  Weight
0  Abdulkareem   23      M   34.00
1         Khem   18      M   12.67
2        Adams   26   Male    9.30

In [ ]:
print(df["Age"].mean())
print(df["Age"].sum())
print(df["Age"].count())

22.333333333333332
67
3