In [6]:
import pandas as pd

dic = {
    "Name": ["Abdulkareem", "Khem", "Adams"],
    "Age": [23, 18, 26],
    "Gender": ["Male", "Female", "Male"],
}

df = pd.DataFrame(dic)

df

          Name  Age  Gender
0  Abdulkareem   23    Male
1         Khem   18  Female
2        Adams   26    Male

In [9]:
df.iloc[0]

Name      Abdulkareem
Age                23
Gender           Male
Name: 0, dtype: object

In [10]:
type(df.iloc[0])

pandas.core.series.Series

In [11]:
df["Age"]

0    23
1    18
2    26
Name: Age, dtype: int64

In [12]:
type(df["Age"])

pandas.core.series.Series

In [17]:

print(df)
print(df.describe())

          Name  Age  Gender
0  Abdulkareem   23    Male
1         Khem   18  Female
2        Adams   26    Male
             Age
count   3.000000
mean   22.333333
std     4.041452
min    18.000000
25%    20.500000
50%    23.000000
75%    24.500000
max    26.000000

In [23]:
dic = {
    "Name": ["Abdulkareem", "Khem", "Adams"],
    "Age": [23, 18, 26],
    "Gender": ["Male", "Female", "Male"],
    "Weight": [34,12.67,9.3]
}

df = pd.DataFrame(dic)

print(df)
df.describe()

          Name  Age  Gender  Weight
0  Abdulkareem   23    Male   34.00
1         Khem   18  Female   12.67
2        Adams   26    Male    9.30

             Age     Weight
count   3.000000   3.000000
mean   22.333333  18.656667
std     4.041452  13.394127
min    18.000000   9.300000
25%    20.500000  10.985000
50%    23.000000  12.670000
75%    24.500000  23.335000
max    26.000000  34.000000